version: '3.8'

services:
  maxscale:
    image: mariadb/maxscale:latest
    ports:
      - "4006:4006"
      - "6603:6603"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    restart: always
  
  master1:
    image: mariadb:latest
    command: --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
    volumes:
      - ./master1.cnf:/etc/mysql/conf.d/master.cnf
      - ./data1:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  master2:
    image: mariadb:latest
    command: --server-id=2
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
    volumes:
      - ./master2.cnf:/etc/mysql/conf.d/master.cnf
      - ./data2:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
